version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
        - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
        - ./data/grafana/:/var/lib/grafana/
    ports:
        - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
        - "9090:9090"
    command:
        - --config.file=/etc/prometheus/prometheus.yml
    volumes:
        - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - ./data/prometheus:/prometheus 