version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
        - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
        - ./data/grafana/:/var/lib/grafana/
    ports:
        - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
        - "9090:9090"
    command:
        - --config.file=/etc/prometheus/prometheus.yml 
    volumes:
        - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - ./config/prometheus/host.json:/etc/prometheus/host.json
        - ./data/prometheus:/prometheus 

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/:/etc/loki
      - ./data/loki/:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    restart: unless-stopped
    depends_on:
      - grafana