global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: 192.168.2.167:9100
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.2.167:9100
