global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: 进程1
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.1.137:9100
    - job_name: node_进程1
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.1.137:9200
