global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: '监控服务列表'
      file_sd_configs:
        - files:
          - /etc/prometheus/host.json
          refresh_interval: 10s 
